version: "3.8"
services:
  nginx:
    image: nginx:1-alpine
    ports:
      - 8089:80
    volumes:
      - ./front/:/usr/share/nginx/html
    depends_on:
      - backend

  backend:
    image: node:20.0.0-alpine
    user: node
    tty: true
    stdin_open: true
    working_dir: /home/node
    entrypoint: sh -c
    command: '"npm install && npm run dev"'
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/home/node
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toto
      POSTGRES_DB: mydatabase
    volumes:
      - ./data/datasets:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - db
