version: "3.8"
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx    
    ports:
      - 8078:80
      - 44378:443
    volumes:
      - ./front/:/usr/share/nginx/html
      - ./certbot/letsencrypt/etc:/etc/letsencrypt
      - ./logs/nginx:/var/log/nginx      
    entrypoint: sh -c '/wait-for-cert.sh'
    depends_on:
      - backend

  backend:
    container_name: backend
    image: node:20.0.0-alpine
    user: node
    tty: true
    stdin_open: true
    working_dir: /home/node
    entrypoint: sh -c
    command: '"npm install && npm run dev"'
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/home/node
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toto
      POSTGRES_DB: mydatabase
    volumes:
      - ./data/datasets:/docker-entrypoint-initdb.d

  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - 8080:8080
    volumes:
      - ./logs/adminer:/var/log/adminer
    depends_on:
      - db

  certbot:
    container_name: certbot
    image: certbot/dns-cloudflare        
    command: >-
      certonly
      --non-interactive
      --dns-cloudflare
      --dns-cloudflare-credentials /opt/cloudflare/credentials.ini
      --dns-cloudflare-propagation-seconds 30
      --email lo.gauthier.glo@gmail.com
      --agree-tos --no-eff-email      
      -d ualtarh.dev  
      -d *.ualtarh.dev  
      --dry-run
    volumes:
      - ./certbot/credentials.ini:/opt/cloudflare/credentials.ini
      - ./certbot/letsencrypt/etc:/etc/letsencrypt
      - ./certbot/letsencrypt/log:/var/log/letsencrypt

  certbot_cron:
    container_name: certbot_cron
    build:
      context: ./certbot_cron
    volumes:
      - ./certbot:/opt/cloudflare
      - ./certbot/letsencrypt/etc:/etc/letsencrypt
      - ./certbot/letsencrypt/log:/var/log/letsencrypt

  fail2ban:
    image: lscr.io/linuxserver/fail2ban:latest
    container_name: fail2ban
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./fail2ban/config:/config
      - ./logs/nginx:/remotelogs/nginx:ro
      - ./logs/adminer:/remotelogs/adminer:ro

  endlessh:
    image: lscr.io/linuxserver/endlessh:latest
    container_name: endlessh
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - LOGFILE=TRUE
    volumes:
      - ./endlessh/logs:/config/logs
    ports:
      - 22:2222
    restart: unless-stopped

  samba:
    image: elswork/samba:latest
    container_name: samba
    environment:
      - TZ=Europe/Paris
    ports:
      - 139:139
      - 445:445
    volumes:
      - ../sambaTest:/share/data
    command: >
      -u "1000:1000:mathieup:mathieup:141546"
      -s "Mathieu (sambaTest):/share/data/mathieup:rw:mathieup"
