version: "3.8"
services:
  nginx:
    image: nginx:1-alpine
    ports:
      - 8089:80
      - 443:443
    volumes:
      - ./front/:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/data/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend

  backend:
    image: node:20.0.0-alpine
    user: node
    tty: true
    stdin_open: true
    working_dir: /home/node
    entrypoint: sh -c
    command: '"npm install && npm run dev"'
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    volumes:
      - ./backend:/home/node
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toto
      POSTGRES_DB: mydatabase
    volumes:
      - ./data/datasets:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - db

  certbot:
    image: "infinityofspace/certbot_dns_duckdns:latest"
    container_name: "certbot_dns_duckdns"
    volumes:
      - "./certbot/data/letsencrypt:/etc/letsencrypt"
      - "./certbot/data/logs:/var/log/letsencrypt"
    command: certonly
      --non-interactive
      --agree-tos
      --email mathieupannetrat5@gmail.com
      --preferred-challenges dns
      --authenticator dns-duckdns
      --dns-duckdns-token d2c8649e-31f2-4a28-8ee6-0fc52d98f69e
      --dns-duckdns-propagation-seconds 30
      -d mapa-project.duckdns.org

  certbot_cron:
    build:
      context: ./certbot-cron
    container_name: "certbot_cron"
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - CERTBOT_CONTAINER_NAME=certbot_dns_duckdns
